# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev_explore',
                'doc_host': 'https://yaminabes.github.io',
                'git_url': 'https://github.com/yaminabes/nbdev_explore',
                'lib_path': 'nbdev_explore'},
  'syms': {'nbdev_explore.core': {'nbdev_explore.core.foo': ('core.html#foo', 'nbdev_explore/core.py')}}}
